### ISSUE TITLE
separating model definition from observations?

### ISSUE THREAD

**Issue by yarden** [pymc-devs/pymc2#10]
Hi,

I wanted to see if it's possible with the current pymc design to separate observations of random variables's values in a probabilistic model from the definition of the model itself. If not, I think it would be a useful feature to add in future. The syntax I imagine would separaet model definition from observations similarly to how the Church/Venture/Anglican probabilistic languages do [1].  Is this separation possible in pymc?  Consider the rain-umbrella Bayes net from AIMA [2], which I wrote in `pymc`:

```
import pymc
import numpy as np

rain = pymc.Bernoulli("rain", 0.5)

def umbrella_logp(value, rain):
    """
    Umbrella node. Initial value is False.

    P(umbrella=True | rain=True)  = 0.9 
    P(umbrella=True | rain=False) = 0.2
    """
    p_umb_given_rain = 0.9
    p_umb_given_no_rain = 0.2
    if rain:
        logp = pymc.bernoulli_like(value, p_umb_given_rain)
    else:
        logp = pymc.bernoulli_like(value, p_umb_given_no_rain)
    return logp

# declare umbrella as observed, with value True
umbrella = pymc.Stochastic(name="umbrella",
                           doc="umbrella var",
                           parents={"rain": rain},
                           logp=umbrella_logp,
                           value=True,
                           observed=True)
rain_hmm = pymc.Model([rain, umbrella])
m = pymc.MCMC(rain_hmm)
m.sample(iter=5000)
print "\n"
print "rain: "
print np.mean(m.trace("rain")[:])
```

The above model codes the conditional dependencies and runs inference for the case where the `umbrella` node is observed to be true. However, it'd be nice to take the model and then run inference in it with different sets of observations, without creating new nodes and new Model() instances.  E.g. run inference in same model where other nodes are observed, like `rain` instead of `umbrella`, or where `umbrella` is observed to be false instead of true. 

I tried instead making the stochastic nodes unobserved when defining them (`observed=False`) and then setting their value using the `.value` attribute, which the manual says is the right way to change values of nodes (http://pymc-devs.github.io/pymc/modelbuilding.html).  That didn't work: nodes that are observed seem to have to be declared as observed from the start, and once they're observed, their values can't change.  

Is there a way to achieve this separation?  Something along the lines of:

```
umbrella = pymc.Stochastic(name="umbrella",
                           doc="umbrella var",
                           parents={"rain": rain},
                           logp=umbrella_logp,
                           random=...)
# define the model, make no references to 'observe='
rain_hmm = pymc.Model([rain, umbrella])
# set observations if any, e.g.
rain_hmm.observe("rain", value=True)
rain_hmm.observe("other_node", ...)  # observe other nodes
# do inference
m = pymc.MCMC(rain_hmm)
...
# now set a new observations, without changing model
rain_hmm.observe("rain", value=np.na)  # rain not observed
rain_hmm.observe("umbrella", value=False) 
```

Thanks. 

[1] See "Inference" section in: http://www.robots.ox.ac.uk/~fwood/anglican/examples/bayes_net/index.html for simple example of separation between model assumptions ("assume" statements) and observations ("observe" statements).

[2] The Bayes net itself is given here: http://en.wikipedia.org/wiki/Forward%E2%80%93backward_algorithm#Example - I only wrote it up for a single time step above

**Comment by fonnesbeck** [comment]
I think something along these lines would be feasible. Perhaps the most sensible way would be to change `Stochastic.set_value` method to accept an `observed` flag.

```
umbrella.set_value(True, observed=True)
```

I'm not opposed to your solution either, however, where it is set via the model rather than the stochastic. No reason we can't have both, I suppose. All this would have to do is move stochastics to and from the Model.stochastics and Model.observed_stochastics dictionaries.

**Comment by yarden** [comment]
Either way sounds great. I'd be happy to try to implement this. Should it go in pymc or pymc3? I'm not totally sure of the relationship between the two - is pymc3 meant to replace pymc very soon? Is the plan to have pymc3 be backwards compatible with pymc?

**Comment by fonnesbeck** [comment]
You can try to implement it in either version, though `pymc` will be easiest. `pymc3` will eventually replace `pymc`, but they are likely to coexist for some time. It is a breaking update; though the syntax is very similar, you cannot simply run a `pymc` model under `pymc3`.

**Comment by marcus-r-kelly** [comment]
I would also be interested in this feature for similar reasons to Yarden-- I am training a model with a given set of observations, and then testing how well other observations fit that model. In particular, it would be really useful to have a function to evaluate the logp of a model given observations that are not extrinsic to the model itself. Perhaps these could even be optional arguments passed to the logp function

``` python
@stochastic(observed=True)
def my_distribution(**kwargs):
    #etc.

my_distribution.logp
#^^ would evaluate with values used at initialization
my_distribution.logp(other_vaues)
#^^ evaluates with values =  other_values instead of those used at initialization
```

**Comment by tom-christie** [comment]
I would also love to have this feature!  It would be nice to see how the posterior shifts as new data is observed.

**Comment by fonnesbeck** [comment]
What I generally do is wrap my model in a function, and use the dataset as an argument. That way, each instance of the model is associated with the new dataset. e.g.

``` python
def generate_model(dataset):

    <model declaration>

    # Likelihood
    y = Normal('y', mu, tau, value=dataset['y'], observed=True)

    return locals()

model1 = MCMC(generate_model(dataset1))
model2 = MCMC(generate_model(dataset2))
```
