### ISSUE TITLE
Inconsistency in Gelman-Rubin documentation

### ISSUE THREAD

**Issue by joergdietrich** [pymc-devs/pymc2#100]
https://pymc-devs.github.io/pymc/modelchecking.html#formal-methods defines Rhat as sqrt(Vhat/W) while the doc string gives Vhat/W, which is what the function actually returns. Gelman & Rubin (1992) define the potential scale reduction as sqrt(Vhat/W) and call that sqrt(Rhat).

Incidentially pymc3 returns sqrt(Vhat/W).

**Comment by fonnesbeck** [comment]
Thanks. The PR above should fix this.

**Comment by joergdietrich** [comment]
Looks good. I wasn't sure whether you'd prefer a change of the docs or of the API.
