### ISSUE TITLE
Issue with degenerate beta binomial?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc2#114]
In the limit of b -> 0, we expect (AFAIK) the beta binomial distribution to approach a delta distribution with E(x) = n a / (a + b) ->  n.  However, I find that the log likelihood of the beta binomial actually gives a discrete uniform when b=0.  See driver code below and output figures of the pmf.  

```
import numpy as np
import pymc as pm

a = 10.
n = 4
xgrid = np.arange(5)

for i, b in enumerate([1E-2, 1E-5, 0.0]):
  logprobs = np.array([pm.betabin_like(x, a, b, n) for x in xgrid])
  probs = np.exp(logprobs)
  plt.figure()
  plt.title(str(b))
  plt.plot(xgrid, probs, label=str(b))
  plt.ylim(-0.1, 1.1)
  plt.savefig("./%d.png" % i)

```

![image](https://cloud.githubusercontent.com/assets/1900459/14906291/bb6b6222-0d6e-11e6-9b4b-8e20f00b55c8.png)

![image](https://cloud.githubusercontent.com/assets/1900459/14906295/c1c2ae64-0d6e-11e6-897e-844d6cda2c97.png)

![image](https://cloud.githubusercontent.com/assets/1900459/14906297/c64273b6-0d6e-11e6-9afc-6c98f85a8cab.png)

**Comment by kyleabeauchamp** [comment]
Tested on OSX + anaconda2.7 + pymc 2.3.6 + numpy 1.10.4

**Comment by kyleabeauchamp** [comment]
Also notice that the logP isn't even properly normalized in the case of b=0.0

**Comment by kyleabeauchamp** [comment]
AFAIK I think the relevant code is here:

https://github.com/pymc-devs/pymc/blob/master/pymc/flib.f#L4224

**Comment by kyleabeauchamp** [comment]
After applying PR #115, I get the following output from the above driver script:

![0](https://cloud.githubusercontent.com/assets/1900459/14934138/555f6f7a-0e5c-11e6-9583-d65cd9dae683.png)

![1](https://cloud.githubusercontent.com/assets/1900459/14934140/5a54ab30-0e5c-11e6-9755-8fa4ef002a16.png)

![2](https://cloud.githubusercontent.com/assets/1900459/14934141/5ce8901e-0e5c-11e6-97e9-9537b8d1b08f.png)

**Comment by kyleabeauchamp** [comment]
Obviously this is stretching the notation a bit, as most people probably require positive values on the parameters.  On the other hand, extending the domain a bit is probably better than silently return a wrong answer.

**Comment by fonnesbeck** [comment]
That's fine. The log-likelihoods were primarily intended to power MCMC, so simply returning -inf for parameters that are zero makes sense most of the time. The fact that negative `a` and `b` values are being admitted in some circumstances in the new code has me a little worried.

**Comment by kyleabeauchamp** [comment]
Good catch, see #116
