### ISSUE TITLE
What is the Markov blanket of a node in pymc?

### ISSUE THREAD

**Issue by yarden** [pymc-devs/pymc2#13]
Hi,

I set up a simple model in PyMC with two stochastic nodes, one node (`rain`) being the parent of the other (`umbrella`), i.e. `rain -> umbrella`. For some reason, there's no Markov blanket calculated for the `umbrella` node and the `rain` node's Markov blanket includes `umbrella` and `rain` itself. I expected the Markov blanket of `rain` to be: `{umbrella, rain}` and the Markov blanket of `umbrella` to be `{rain}`. What is PyMC's definition of a Markov blanket? Is there an implementation of the traditional definition of a Markov blanket (the node's parents, children and parents of its children)? As in: http://en.wikipedia.org/wiki/Markov_blanket

This is the code to print Markov blankets for the model:

```
import pymc
import numpy as np
rain = pymc.Bernoulli("rain", 0.5)
def umbrella_logp(value, rain):
    p_umb_given_rain = 0.9
    p_umb_given_no_rain = 0.2
    if rain:
        logp = pymc.bernoulli_like(value, p_umb_given_rain)
    else:
        logp = pymc.bernoulli_like(value, p_umb_given_no_rain)
    return logp
# Observed node
umbrella = pymc.Stochastic(name="umbrella",
                           doc="umbrella var",
                           parents={"rain": rain},
                           logp=umbrella_logp,
                           observed=True,
                           value=True)
rain_model = pymc.Model([rain, umbrella])
for k in rain_model.markov_blanket:
    print "Markov blanket for ", k, " is ", rain_model.markov_blanket[k]
```

which outputs:

```
Markov blanket for  rain  is  set([<pymc.distributions.Bernoulli 'rain' at 0x10bfde9d0>, <pymc.PyMCObjects.Stochastic 'umbrella' at 0x10bfde8d0>])
```

so `umbrella` is missing but `rain` looks right.

**Comment by fonnesbeck** [comment]
The Markov blanket is not calculated for observed stochastics, because it is not really used for anything (since the node is observed).

**Comment by yarden** [comment]
Makes sense, thanks for the clarification.
