### ISSUE TITLE
Speak at a meetup?

### ISSUE THREAD

**Issue by earino** [pymc-devs/pymc2#144]
Greetings!

I am keenly aware that this is not the appropriate place to ask this question, and I wanted to open with my deep apologies. I run the Los Angeles Python Data Science meetup. We have a travel budget and I (and the 100s of pythonistas who come to our meetups) are fascinated by the ongoing work in pymc! Is there any chance I could get one of the pymc-devs to come to LA to speak at our meetup? We would pay for flight/hotel!

I couldn't find another way to address the group, so again, my apologies for this misuse of github issues.

Cheers! Feel free to email me at earino at gmail or respond however you wish.

Eduardo

**Comment by fonnesbeck** [comment]
Hi Eduardo. I would be available depending on when you were thinking (I live in Nashville). Others from the PyMC3 group (most of the development action is on that project now) might also be available, depending on what aspect of the project you are interested in. My email contact is my last name at gmail.com if you want to get in touch.
