### ISSUE TITLE
Conda installs old version

### ISSUE THREAD

**Issue by PAGWatson** [pymc-devs/pymc2#146]
Hello, I'm not sure if this is the best place to report this, but I tried installing pymc using conda, with command "conda install pymc", and it installed version 2.3.3. This required me to downgrade numexpr, numpy, scikit-learn and scipy to quite old versions, which wouldn't import correctly afterwards. Doing "conda search pymc" shows there are later pymc versions available, and everything worked fine after I upgraded to 2.3.6 and the other modules were upgraded to recent versions again. Why is the default version installed by conda one that is old and that forces users to downgrade other important modules?

**Comment by fonnesbeck** [comment]
You are correct. The conda recipe is out of date. I will look into getting it updated.

**Comment by fonnesbeck** [comment]
Working on it [here](https://github.com/conda-forge/staged-recipes/pull/2226). Will let you know when it is ready.

**Comment by PAGWatson** [comment]
Great, thank you.

**Comment by fonnesbeck** [comment]
This should be [fixed now](https://github.com/conda-forge/staged-recipes/pull/2233#event-928213140). Try installing from conda, and reopen if there are issues.
