### ISSUE TITLE
Is there score based structure learning approachs for bayesian network in this package?

### ISSUE THREAD

**Issue by faeahi** [pymc-devs/pymc2#148]
Hello.
I want to learn bayesian network from a dataset with continuous values and i need to use score based approachs for structure learning.
I want to know is there score based structure learning approachs for this in this package?
Is there parameter learning approach for such values?

Thanks.

**Comment by fonnesbeck** [comment]
PyMC is for solving models using MCMC. So, if you can specify your model (see documentation) in PyMC, you can use these methods to fit it. It does not use other ML fitting methods.
