### ISSUE TITLE
Error installing pymc with pip

### ISSUE THREAD

**Issue by paraguz1** [pymc-devs/pymc2#149]
I get the following error when trying to install pymc with pip:

No such file or directory:  'lapack/double/dpotrs.f'

I have installed Mingw with fortran compiler and tried other ways to install pym: 
- using msys and python py.setup install ( I get the same lapack error)
- anaconda tool  (the module is intalled but I get an error with container_values module when trying to import pymc module)
- easy install   (the module is intalled but I get an error with container_values module when trying to import pymc module)
I can not find a way to install it.
I'm using python 2.7 and windows 7 system.

Maybe you could help me with the lapack issue.
Thank you.

![image](https://cloud.githubusercontent.com/assets/22820924/22408704/83de926e-e67d-11e6-9aa8-c91ee0b2d9be.png)

**Comment by fonnesbeck** [comment]
Haven't seen this before. My experience is that Fortran errors tend to be related to compiler incompatibility. If you are on Anaconda, you should be able to install a Windows binary, no?

Also, you might check out PyMC3, since it has recently been released and supercedes PyMC 2.3.

**Comment by paraguz1** [comment]
Thank you I'll try to install with Anaconda again or use the new release.

**Comment by fonnesbeck** [comment]
I will close this. Please report back if there are ongoing issues.

**Comment by tuxdna** [comment]
I encountered same issue on Fedora 25:

```
    compile options: '-Ibuild/src.linux-x86_64-2.7 -I/usr/lib64/python2.7/site-packages/numpy/core/include -I/usr/include/python2.7 -c'
    error: [Errno 2] No such file or directory: 'lapack/double/dpotrs.f'
    
    ----------------------------------------
```

From a related [StackOverflow post](https://stackoverflow.com/questions/40444289/error-installing-pymc-on-debian-sid) it seemed like the issue is with missing development libraries. `sudo apt-get install liblapack-dev`

For Fedora I had to install the development library as below:

```
$ sudo dnf install lapack-devel
```

That fixes the installation issue for me.

**Comment by kannte** [comment]
sudo apt-get install liblapack-dev
this worked for me , thanks,

**Comment by shangxww** [comment]
I encounted same issue in win7 when i install with command "pip install pymc" , i wonder it is not a lasted version when i use this command to install it?
And like mentioned above, how to execute this *If you are on Anaconda, you should be able to install a Windows binary** to install a binary build.

**Comment by shangxww** [comment]
> Sorry to  disturb you , i wonder ,if this issues has resolved in you pc. if yes, would you please show command you used.

**Comment by fonnesbeck** [comment]
pip will build from source, so its not surprising that it does not work on Windows without your system being configured properly. If you install Anaconda, you should just be able to `conda install pymc`.

Are you sure you mean to be installing PyMC2? We recommend most users install PyMC3 instead--it is a separate project.
