### ISSUE TITLE
No module named pymc with Anaconda in Win764

### ISSUE THREAD

**Issue by ghost** [pymc-devs/pymc2#15]
I am unable to properly install pymc with my Anaconda setup.
Using the latest  Anaconda 3.1 (build 1.8.2)
Python is 2.7.8 (latest available through Anaconda).
Tried installing both with pip and conda.
Spyder gives no module named pymc when doing import.
Version of pymc being installed is 2.3.4.

**Comment by fonnesbeck** [comment]
Can you report what information is in the terminal when the install fails? Does the install fail, or is it successful and it just fails to import?

**Comment by ghost** [comment]
Thanks for trying to help
I had two terminals and I install on the other one....
Thanks again

On Tue, Mar 24, 2015 at 11:06 PM, Chris Fonnesbeck <notifications@github.com
