### ISSUE TITLE
Same EOF errors using pip, easy_install, and source installation

### ISSUE THREAD

**Issue by reventropy** [pymc-devs/pymc2#151]
Line #159 in pymc/gibbsit.f:"      parameter (maxseries=20)"
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Line #162 in pymc/gibbsit.f:"      parameter (maxqcnt=20)"
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Line #162 in pymc/gibbsit.f:"      parameter (maxqcnt=20)"
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Line #196 in pymc/gibbsit.f:"      parameter (wasize=maxiterates*2)"
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Line #196 in pymc/gibbsit.f:"      parameter (wasize=maxiterates*2)"
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''
Line #196 in pymc/gibbsit.f:"      parameter (wasize=maxiterates*2)"
	get_parameters: got "unexpected EOF while parsing (<string>, line 0)" on ''

**Comment by reventropy** [comment]
Other details:

DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=18
DISTRIB_CODENAME=sarah
DISTRIB_DESCRIPTION="Linux Mint 18 Sarah"
NAME="Ubuntu"
VERSION="16.04 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian


Python 2.7.12
I've checked that all dependencies are satisfied.

**Comment by fonnesbeck** [comment]
Not sure about this. Which Fortran compiler are you using? Does this occur on Python3?

**Comment by reventropy** [comment]
Thanks for the response.  I'm using gfortran 5.4.0.  I've successfully installed Pymc 3, but the module I'm interested in using depends on Pymc 2.

**Comment by reventropy** [comment]
I don't currently have python 3 installed, but it's worth a shot.

**Comment by fonnesbeck** [comment]
Is it possible for you also to try gcc/gfortran 6.2+?

**Comment by reventropy** [comment]
I'll try that next.  I just tried a pip install on Python 3 and got the same EOF errors in addition to this:

	/usr/local/lib/python3.5/dist-packages/numpy/distutils/system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    IOError: [Errno 2] No such file or directory: 'skip:ppnd7'. Skipping file "skip:ppnd7".
    updatevars:gradlike: attempt to change 'dimension(nx)' to 'dimension(na)'. Ignoring.
    updatevars:gradlike: attempt to change 'dimension(nx)' to 'dimension(nb)'. Ignoring.
    updatevars:gradlike: attempt to change 'dimension (nmu)' to 'dimension(nmu)'. Ignoring.
    updatevars:gradlike: attempt to change 'dimension (na)' to 'dimension(na)'. Ignoring.
    rmbadname1: Replacing "index" with "index_bn".

**Comment by reventropy** [comment]
Upgraded gcc to 6.2.  Same issue..  I was able to install it without issue on a machine running CentOS6. Was hoping to install it on my laptop but I'll move on for now..

**Comment by fonnesbeck** [comment]
OK, sorry about that. I will leave the issue open.

I encourage you to look at PyMC3, unless you have a good reason to stay with PyMC 2.x. There are some much more efficient samplers in the newer package.

**Comment by vanzod** [comment]
This is the same I reported with issue #150. I will close that one and keep the discussion here.

**Comment by dataoverflow** [comment]
Same problem here with Ubuntu 16.04.2/Python3.5. Creating a separate virtual env where I first installed older numpy followed by pymc somewhat solves the problem:

```
pip install numpy==1.10.1
pip install pymc
```

The latest numpy breaks compatibility?

**Comment by fonnesbeck** [comment]
It looks like the current master of Numpy fixes this. I was able to replicate this issue in 1.12 (the current conda version), but updating to master via pip allows PyMC to be installed. Please confirm:

    pip install -U git+https://github.com/numpy/numpy.git

**Comment by dataoverflow** [comment]
Thanks Chris, I can confirm that installing numpy from master branch solves the problem.

**Comment by fonnesbeck** [comment]
Thank you for confirming.
