### ISSUE TITLE
Sampling MCMC objects lead to memory leak

### ISSUE THREAD

**Issue by tsh56** [pymc-devs/pymc2#167]
```
import gc
import pymc


gc.collect()

foo= pymc.Bernoulli('foo', .3, value=[1])

model = pymc.Model([foo])

mcmc = pymc.MCMC(model)
mcmc.sample(10000, 2000, progress_bar=False)

obj = id(mcmc)
del foo
del model
del mcmc

gc.collect()
for o in gc.get_objects():
    if obj == id(o):
        print 'mcmc still exists'
```

The sample function attaches traces which introduces a circular reference means these object rely on gc to be freed. Unfortunately a numpy.array is part of the circular reference, so we are hitting [this](https://github.com/numpy/numpy/issues/6581) issue.

**Comment by fonnesbeck** [comment]
I can't replicate this here (Python 3.6 on macOS).

**Comment by tsh56** [comment]
I just tested with python 3.6.3 on macOS. The output was "mcmc still exists" meaning that the object was not garbage collected even though all local references foo, model, and mcmc have been deleted.

**Comment by fonnesbeck** [comment]
I get no printed message, so I cannot replicate what you see. 

![](http://d.pr/i/b12HnU+)

Are you on current master?
