### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc2#169]
Any thoughts on a pymc 2.3.7 release?  There have been 86 commits to master since 2.3.6.  A release would also be a good opportunity for me or someone else to fiddle with the conda-forge builds to fix some of the shared library issues observed therein.

**Comment by fonnesbeck** [comment]
Yes, its on my list. Might be able to do it today.

**Comment by fonnesbeck** [comment]
RC1 is tagged. We can move quickly to a release if all looks good.

**Comment by kyleabeauchamp** [comment]
I can confirm that the RC1 tarball installs and imports on my OSX High Sierra miniconda3.6 box.  My current calculations also seem to be running OK.  Currently running  `$ nosetests pymc -v` to see if tests run, will post when complete.

**Comment by kyleabeauchamp** [comment]
```
----------------------------------------------------------------------
Ran 193 tests in 22.756s

OK (SKIP=3)
```
