### ISSUE TITLE
`MCMC.sample` goes over by one when given a non-integer `iter`

### ISSUE THREAD

**Issue by jsw-fnal** [pymc-devs/pymc2#17]
If you give the method `MCMC.sample()` a non-integer parameter `iter`, then the sampler will attempt to take one more sample than `floor(iter)`, resulting in an `IndexError`.

Here is a minimal failing example:

```
import pymc
mcmc = pymc.MCMC(pymc.Model([pymc.Uniform("dummy", lower=0, upper=1)]))
mcmc.sample(iter=2.5)
```

This gives an `IndexError`.  Here is the full output:

```
/home/hepxadmin/miniconda/envs/python/lib/python2.7/site-packages/pymc/database/base.py:282: UserWarning: 
Error tallying dummy, will not try to tally it again this chain.
Did you make all the samevariables and step methods tallyable
as were tallyable last time you used the database file?

Error:

Traceback (most recent call last):
  File "/home/hepxadmin/miniconda/envs/python/lib/python2.7/site-packages/pymc/database/base.py", line 272, in tally
    self._traces[name].tally(chain)
  File "/home/hepxadmin/miniconda/envs/python/lib/python2.7/site-packages/pymc/database/ram.py", line 97, in tally
    self._trace[chain][self._index[chain]] = value.copy()
IndexError: index 2 is out of bounds for axis 0 with size 2

  %s""" % (name, ''.join(traceback.format_exception(cls, inst, tb))))
```

This occurs with an Anaconda install of pymc 2.3.3, running on python 2.7.

**Comment by fonnesbeck** [comment]
The `iter` argument should always be an integer. I think I would prefer a failure with a float, and place the responsibility on the user to pass the correct type. However, I can add a more informative error message.

**Comment by jsw-fnal** [comment]
It'd be easy to just slap a `floor(iter)` in, right?  Maybe add a warning?  I ask because I often do things like:

```
Nsamp = 100000
mcmc.sample(Nsamp*1.1, burn=Nsamp*.1)
```

which enables me to change the number of samples in the final trace easily, while retaining a somewhat-reasonable burn-in period.

**Comment by fonnesbeck** [comment]
OK, fair enough. Just pushed a fix, and will merge once it passes the tests.
