### ISSUE TITLE
Problem with `pymc.Lambda` using 2.3.7.rc1

### ISSUE THREAD

**Issue by ian-r-rose** [pymc-devs/pymc2#172]
I have a model that I am creating using `pymc.Lambda`. Depending upon the context, it can have a variable number of parameters, so I have packed them into an argument list, so the construction of the deterministic looks something like
```python
deterministic = pymc.Lambda('name', lambda args=args: do_stuff(*args))
```
This works as expected in 2.3.6, but when I was testing 2.3.7.rc1 I got the error
```python
ValueError: name: All arguments to lam_fun must have default values.
```

So far as I can tell, the problem is due to [this](https://github.com/pymc-devs/pymc/commit/60b464fd65a84edfa8da787a161217d4d79e8b74#diff-c3991a57a8ce4b5a39e7adb631ec3a4fR50) change, where arguments with the names `args` and `kwds` are special-cased.

I fixed my problem by renaming the lambda argument, but only after some digging. Is there perhaps another way to do this that doesn't rely on special argument names? If not, perhaps we can add a warning to the docstring for `Lambda`?

**Comment by fonnesbeck** [comment]
Hi Ian. If you want to go ahead and do a PR that does what you need and not regress the issue in #76 I would be happy to merge it.
