### ISSUE TITLE
import pymc not working

### ISSUE THREAD

**Issue by jacksbd2** [pymc-devs/pymc2#177]
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-be432c90d05f> in <module>()
----> 1 import pymc

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pymc\__init__.py in <module>()
     28 from .PyMCObjects import *
     29 from .InstantiationDecorators import *
---> 30 from .CommonDeterministics import *
     31 from .NumpyDeterministics import *
     32 from .distributions import *

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pymc\CommonDeterministics.py in <module>()
     19 import inspect
     20 import types
---> 21 from .utils import safe_len, stukel_logit, stukel_invlogit, logit, invlogit, value, find_element
     22 from copy import copy
     23 import sys

~\AppData\Local\Continuum\anaconda3\lib\site-packages\pymc\utils.py in <module>()
     12 from copy import copy
     13 from .PyMCObjects import Variable
---> 14 from . import flib
     15 import pdb
     16 from numpy.linalg.linalg import LinAlgError

ImportError: DLL load failed: The specified procedure could not be found.

**Comment by fonnesbeck** [comment]
Please provide more information: 
- platform you are using
- version of PyMC you are using
- version of Python you are using

Also, are you intending to use PyMC2? We recommend most users to work with PyMC3, which is a different repository.

**Comment by jacksbd2** [comment]
Hi Chris,

Thanks for the response.

I'm using Anaconda 1.8.5

with Jupyter 5.5.0

running Python 3.6.4 64 bit

on a Windows 10 platform.

I installed pymc via my Anaconda Navigator environment.


I'm working with some pre-existing code that imports PyMC 2


My goal is to recreate a MCMC dynamic factor switching model for classification of economic recessions v. expansions


If PyMC 3 can be substituted, that would be great, but the syntax looked a little bit different.


Any suggestions you can provide would be appreciated, thanks!

Bruce


Bruce Jackson

(651) 315-2260[cid:2c478e0e-8dce-4bda-a2cc-de42626d3725]

jack3604@stthomas.edu

________________________________

**Comment by fonnesbeck** [comment]
If you can, try creating a clean conda environment, activate it, and install PyMC in that environment and see if this still happens. 

PyMC 2 Code does not run unchanged under PyMC3, but its not hard to port (usually). If you are looking to do substantial development, it would e worth looking at PyMC3, as it is far more capable.

**Comment by jacksbd2** [comment]
I suspect issue was with fortran compiler and Anaconda.  I'm working in PyMC3 now, thanks!
