### ISSUE TITLE
pymc.test() error

### ISSUE THREAD

**Issue by mgdreamingstar** [pymc-devs/pymc2#183]
I installed pymc using anaconda. It can be import in python, but can't pass the pymc.test().
I got this error.
![pymc.test() error](https://user-images.githubusercontent.com/26304780/44629987-a8a80f00-a989-11e8-9ffb-a2bcb2c11443.png)

**Comment by fonnesbeck** [comment]
I cannot replicate this on Linux (Debian) or macOS (using conda release version). Can you make sure you are in a clean conda env?

**Comment by mgdreamingstar** [comment]
I create a new conda environment and install pymc using conda. I'm using WIN10, and always get this error.

**Comment by abhisheshpal** [comment]
I have installed pymc for python 2.7. the import in python is ok but problem with the pymc.test(). I am getting error mention below: 

![image](https://user-images.githubusercontent.com/24971359/52335785-24a78800-29fb-11e9-9df2-84616eacba19.png)

**Comment by fonnesbeck** [comment]
This is a matplotlib error, not a PyMC error.
