### ISSUE TITLE
Can't install PyMC neither through conda nor pip on Windows 7

### ISSUE THREAD

**Issue by mayankkaizen** [pymc-devs/pymc2#184]
I have Anaconda on Windows 7. Python version is 3.6. I ran `conda install pyMC` and it showed following errors - 

    UnsatisfiableError: The following specifications were found to be in conflict:
      - pymc
      - yellowbrick -> scikit-learn >=0.19
    Use "conda info <package>" to see the dependencies for each package.

Using is pip also didn't solve the problem. I ran `pip install pymc` and it threw quite a long error message. I am pasting last part of message here - 

        running build_ext
        No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
        customize MSVCCompiler
        customize MSVCCompiler using build_ext
        get_default_fcompiler: matching types: '['gnu', 'intelv', 'absoft', 'compaqv
    ', 'intelev', 'gnu95', 'g95', 'intelvem', 'intelem', 'flang']'
        customize GnuFCompiler
        Could not locate executable g77
        Could not locate executable f77
        customize IntelVisualFCompiler
       Could not locate executable ifort
       Could not locate executable ifl
        customize AbsoftFCompiler
        Could not locate executable f90
        customize CompaqVisualFCompiler
        Found executable c:\cygwin\bin\DF.exe
        customize IntelItaniumVisualFCompiler
        Could not locate executable efl
        customize Gnu95FCompiler
        Could not locate executable gfortran
        Could not locate executable f95
        customize G95FCompiler
        Could not locate executable g95
        customize IntelEM64VisualFCompiler
        customize IntelEM64TFCompiler
        Could not locate executable efort
        Could not locate executable efc
        customize PGroupFlangCompiler
        Could not locate executable flang
        don't know how to compile Fortran code on platform 'nt'
        warning: build_ext: f77_compiler=None is not available.

        building 'pymc.flib' extension
        error: extension 'pymc.flib' has Fortran sources but no Fortran compiler found

        ----------------------------------------
    Command "c:\miniconda3\envs\data\python.exe -u -c "import setuptools, tokenize;_
    _file__='C:\\Users\\Sam\\AppData\\Local\\Temp\\pip-install-mp8kw1h2\\pyMC\\se
    tup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n'
    , '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Use
    rs\Sam\AppData\Local\Temp\pip-record-zt5fxwzt\install-record.txt --single-ver
    sion-externally-managed --compile" failed with error code 1 in C:\Users\Sam\A
        ppData\Local\Temp\pip-install-mp8kw1h2\pyMC\

Don't know what is going on and what to do?

**Comment by fonnesbeck** [comment]
I’ve not seen the conda error before. Can you try installing into a clean conda env? 

Installing via pip is tricky on windows—see the docs for details. 

Are you intending to install PyMC 2? We recommend that users run PyMC 3 unless there is a reason not to.

**Comment by mayankkaizen** [comment]
@fonnesbeck Though I am not sure what was the problem with `pymc`, I had no issue with installation of `pymc3`. 

Thanks for the reply and this amazing library.
