### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by Toshinaki** [pymc-devs/pymc2#19]
Hi, I want to use python as statistics tool, so after google, I installed some module in python
like numpy, matplotlib, and so on.
And I decided to install pymc......
And it took me one afternoon and one night to get pymc installed.
I did  <pre>import pymc</pre>
and this comes out:

<pre>Traceback (most recent call last):
  File "<pyshell#5>", line 1, in <module>
    import pymc
  File "D:\Programming\Python34\lib\site-packages\pymc\__init__.py", line 27, in <module>
    from .Container import *
  File "D:\Programming\Python34\lib\site-packages\pymc\Container.py", line 41, in <module>
    from .Container_values import LCValue, DCValue, ACValue, OCValue
ImportError: DLL load failed: the specified module could not be found</pre>

I tried depends and it showed that python34.dll is missing.
And I tried adding pymc's path to PATH.
Nothing worked.
I used MinGW for pymc install.
My OS is win8 64-bit.
Please help with this!
Thank you!!

Update------------------------
I tried anaconda
and was shocked.
It got everything installed in less than 3 minutes...
But I spent more than 9 hours to try to read and do things I don't even understand.
Thank you whoever created anaconda.
And thanks to kyleam who told me about anaconda.

Maybe pymc should add this in its documentation:
"If you are using windows, please try anaconda!"
Well, it's just my opinion.^^

**Comment by kyleam** [comment]
I don't run windows, so I can't be of too much help.  But you might want to look into [anaconda](https://store.continuum.io/cshop/anaconda/) to minimize the headaches of installing scientific python packages on windows.

**Comment by Toshinaki** [comment]
So maybe its a good time  to start linux?
I'll try anaconda. Thank you

**Comment by fonnesbeck** [comment]
Anaconda is a smart choice even if you do use Linux. It makes most of these compatibility issues go away, not just for PyMC but for many other packages.
