### ISSUE TITLE
Erroneous documentation for Normal

### ISSUE THREAD

**Issue by thomas-haslwanter** [pymc-devs/pymc2#191]
The function "pm.Normal" uses the keyword "sd".
However, all the documentation gives examples with the keyword "sigma" - which crashed the current version of pymc3  (3.6)
E.g. (Documentation):
````
import pymc3 as pm

X, y = linear_training_data()
with pm.Model() as linear_model:
    weights = pm.Normal('weights', mu=0, sigma=1)
````

**Comment by twiecki** [comment]
You probably meant to open this here instead: https://github.com/pymc-devs/pymc3
