### ISSUE TITLE
Python packages installation error

### ISSUE THREAD

**Issue by mridul-1979** [pymc-devs/pymc2#198]
Hi, I have recently started getting the below error each time I install a new package in conda. I have tried uninstalling and reinstalling anaconda, but the problem hasn't gone. Can anyone please help?

(base) C:\WINDOWS\system32>conda install -c conda-forge pymc3
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: C:\Users\bhard\anaconda3

  added / updated specs:
    - pymc3

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    arviz-0.7.0                |             py_0         1.3 MB  conda-forge
    cftime-1.1.1.2             |   py37hbc2f12b_0         225 KB  conda-forge
    conda-4.8.3                |   py37hc8dfbb8_1         3.1 MB  conda-forge
    hdf4-4.2.13                |       h712560f_2         1.3 MB
    libgpuarray-0.7.6          |    hfa6e2cd_1003         314 KB  conda-forge
    libnetcdf-4.7.3            |       h1302dcc_0         516 KB
    mako-1.1.0                 |             py_0          57 KB  conda-forge
    netcdf4-1.5.3              |   py37h012c1a0_0         353 KB
    pygpu-0.7.6                |py37hc8d92b1_1000         600 KB  conda-forge
    pymc3-3.8                  |             py_0         698 KB  conda-forge
    python_abi-3.7             |          1_cp37m           4 KB  conda-forge
    theano-1.0.4               |py37h6538335_1001         3.7 MB  conda-forge
    vs2015_win-64-14.0.25420   |      h55c1224_11           7 KB
    xarray-0.15.1              |             py_0         487 KB  conda-forge
    ------------------------------------------------------------
                                           Total:        12.6 MB

The following NEW packages will be INSTALLED:

  arviz              conda-forge/noarch::arviz-0.7.0-py_0
  cftime             conda-forge/win-64::cftime-1.1.1.2-py37hbc2f12b_0
  hdf4               pkgs/main/win-64::hdf4-4.2.13-h712560f_2
  libgpuarray        conda-forge/win-64::libgpuarray-0.7.6-hfa6e2cd_1003
  libnetcdf          pkgs/main/win-64::libnetcdf-4.7.3-h1302dcc_0
  mako               conda-forge/noarch::mako-1.1.0-py_0
  netcdf4            pkgs/main/win-64::netcdf4-1.5.3-py37h012c1a0_0
  pygpu              conda-forge/win-64::pygpu-0.7.6-py37hc8d92b1_1000
  pymc3              conda-forge/noarch::pymc3-3.8-py_0
  python_abi         conda-forge/win-64::python_abi-3.7-1_cp37m
  theano             conda-forge/win-64::theano-1.0.4-py37h6538335_1001
  vs2015_win-64      pkgs/main/win-64::vs2015_win-64-14.0.25420-h55c1224_11
  xarray             conda-forge/noarch::xarray-0.15.1-py_0

The following packages will be UPDATED:

  conda                       pkgs/main::conda-4.8.3-py37_0 --> conda-forge::conda-4.8.3-py37hc8dfbb8_1

Proceed ([y]/n)? y

Downloading and Extracting Packages
hdf4-4.2.13          | 1.3 MB    | ############################################################################ | 100%
netcdf4-1.5.3        | 353 KB    | ############################################################################ | 100%
cftime-1.1.1.2       | 225 KB    | ############################################################################ | 100%
arviz-0.7.0          | 1.3 MB    | ############################################################################ | 100%
libnetcdf-4.7.3      | 516 KB    | ############################################################################ | 100%
xarray-0.15.1        | 487 KB    | ############################################################################ | 100%
python_abi-3.7       | 4 KB      | ############################################################################ | 100%
pymc3-3.8            | 698 KB    | ############################################################################ | 100%
vs2015_win-64-14.0.2 | 7 KB      | ############################################################################ | 100%
pygpu-0.7.6          | 600 KB    | ############################################################################ | 100%
theano-1.0.4         | 3.7 MB    | ############################################################################ | 100%
mako-1.1.0           | 57 KB     | ############################################################################ | 100%
conda-4.8.3          | 3.1 MB    | ############################################################################ | 100%
libgpuarray-0.7.6    | 314 KB    | ############################################################################ | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

C:\WINDOWS\system32>SET DISTUTILS_USE_SDK=1

C:\WINDOWS\system32>SET MSSdk=1

C:\WINDOWS\system32>SET platform=

C:\WINDOWS\system32>IF /I [AMD64] == [amd64] set "platform=true"

C:\WINDOWS\system32>IF /I [] == [amd64] set "platform=true"

C:\WINDOWS\system32>if defined platform (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" )  ELSE (set "VSREGKEY=HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio\14.0" )

C:\WINDOWS\system32>for /F "skip=2 tokens=2,*" %A in ('reg query "HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0" /v InstallDir') do SET "VSINSTALLDIR=%B"
ERROR: The system was unable to find the specified registry key or value.

C:\WINDOWS\system32>if "" == "" (set "VSINSTALLDIR=" )

C:\WINDOWS\system32>if "" == "" (
ECHO "WARNING: Did not find VS in registry or in VS140COMNTOOLS env var - your compiler may not work"
 GOTO End
)
"WARNING: Did not find VS in registry or in VS140COMNTOOLS env var - your compiler may not work"
The system cannot find the batch label specified - End

(base) C:\WINDOWS\system32>

**Comment by fonnesbeck** [comment]
It looks like you've posted this to the wrong project. You are looking for pymc3 (pymc-devs/pymc3).
