### ISSUE TITLE
Max number of dim

### ISSUE THREAD

**Issue by psarkis** [pymc-devs/pymc2#32]
I wonder if there is an upper limit on the number of dimensions pymc can handle. My log likelihood is the sum of 3 Gaussians and 1 mixture of Gaussians. Can it handle up to ~ 760 dimensions?

**Comment by fonnesbeck** [comment]
Depends what you mean by dimensions. Your model can have hundreds of parameters (I use models like that all the time), but if there are several array dimensions, it gets very awkward. I recommend using flattened arrays in most cases.
