### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by andyyuan78** [pymc-devs/pymc2#33]
ubgpu@ubgpu:~/github/pymc$ 
ubgpu@ubgpu:~/github/pymc$ sudo python setup.py config_fc --fcompiler gfortran build
ATLAS version 3.10.1 built by buildd on Mon Feb  3 23:10:50 UTC 2014:
............
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize Gnu95FCompiler
customize Gnu95FCompiler using build_ext

ubgpu@ubgpu:~/github/pymc$ sudo python setup.py install
ATLAS version 3.10.1 built by buildd on Mon Feb  3 23:10:50 UTC 2014:
.........
Removing /usr/local/lib/python2.7/dist-packages/pymc-2.3.5.egg-info
Writing /usr/local/lib/python2.7/dist-packages/pymc-2.3.5.egg-info
running install_clib
customize UnixCCompiler
ubgpu@ubgpu:~/github/pymc$ 
ubgpu@ubgpu:~/github/pymc$ 

ubgpu@ubgpu:~/github/pymc$ python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.

> > > import pymc

```
    Warning: You are importing PyMC from inside its source tree.
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pymc/**init**.py", line 27, in <module>
    from .Container import *
  File "pymc/Container.py", line 41, in <module>
    from .Container_values import LCValue, DCValue, ACValue, OCValue
ImportError: No module named Container_values

> > > quit()
> > > ubgpu@ubgpu:~/github/pymc$ python3
> > > Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
> > > [GCC 4.8.2] on linux
> > > Type "help", "copyright", "credits" or "license" for more information.
> > > import pymc

```
    Warning: You are importing PyMC from inside its source tree.
```

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubgpu/github/pymc/pymc/**init**.py", line 27, in <module>
    from .Container import *
  File "/home/ubgpu/github/pymc/pymc/Container.py", line 41, in <module>
    from .Container_values import LCValue, DCValue, ACValue, OCValue
ImportError: No module named 'pymc.Container_values'

**Comment by fonnesbeck** [comment]
You should not attempt to run PyMC from inside the source tree. Change directories and try again.

**Comment by andyyuan78** [comment]
sure, it works.
