### ISSUE TITLE
Erase old docs on readthedocs?

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc2#42]
Google somehow took me to the following page, which is most likely obsolete:

http://pymcmc.readthedocs.org/en/latest/

**Comment by kyleabeauchamp** [comment]
Actually, not sure when those are from

**Comment by fonnesbeck** [comment]
It has a 2014 copyright date, so they can't be that old. At any rate, I'm not the one who put them there so I'm not sure how to change them (I don't have a login at readthedocs.org).

**Comment by kyleabeauchamp** [comment]
Wontfix
