### ISSUE TITLE
Slice sampler gives values outside support of prior

### ISSUE THREAD

**Issue by mcmahanp** [pymc-devs/pymc2#43]
When sampling variables with Uniform or Beta priors in PyMC I'm getting some very strange behavior. The sampler ends up drawing values far, far outside of the support of the prior. Here's a simple example script to reproduce the problem:

```
from pymc import Uniform, Bernoulli, deterministic, MCMC, Metropolis, Slicer
import scipy as sp

n = 1000
p = Uniform('p',0,1)
@deterministic(trace=False)
def probs(p=p):
    return(sp.ones(n)*p)
y = Bernoulli('y',p = probs, value=sp.ones(n),observed=True)
m = MCMC({'p':p,'probs':probs,'y':y})
m.use_step_method(Slicer,m.p) # not necessary as Slicer is the default
m.sample(40)
print('\nMax p: %.5f' % m.p.trace().max())
```

If I run this script I get samples for `p` on the order of 10000. As I understand it the prior should give zero probability for any value outside of [0,1] so this shouldn't be possible -- in fact in this case the posterior distribution for `p` should be Beta(1,1001).

Am I somehow specifying my model incorrectly?

(I'm using the `AdaptiveMetropolis` step method to get around this problem for now, which solves the problem)

I'm using PyMC version 2.3.3 installed using the `conda` command with the Anaconda Python distribution.

**Comment by mcmahanp** [comment]
I dove into this a bit and I found that the problem is with the bernoulli likelihood. While the Uniform stochastic gives a ZeroProbability error for values outside its range, `bernoulli_like` doesn't check its parameters. This gives bad results like:

```
pymc.bernoulli_like(1,p=10) # 2.302585092994046
pymc.bernoulli_like(1,p=-10) # -1.7976931348623157e+308
```

So when the step method calls its `loglike` property in the example from the original post it only asks the Bernoulli variable (y) for its likelihood which doesn't care that the probabilities are nonsensical.

As a somewhat dirty fix I altered `bernoulli_like` to check for bad values of p:

```
def bernoulli_like(x, p):
  try:
    for q in iter(p):
      if q>1 or q<0:
        return(-inf)
  except TypeError:
    # not iterable
    if p>1 or p<0:
      return(-inf)
  return flib.bernoulli(x, p)
```

It doesn't feel right to enforce parameter bounds through the probability density, but the effect should be the same mathematically.

Any chance of a more thorough fix in a future version?

**Comment by fonnesbeck** [comment]
Fixed this in #50. Will merge when it passes tests.

**Comment by mcmahanp** [comment]
Thanks!
Quick question though -- looking at your fix, does it handle when `p` is a standard python list (rather than a numpy array)?

**Comment by fonnesbeck** [comment]
I moved the bounds checking to Fortran, so it should now work with any vector data structure.

**Comment by alebyk113** [comment]
.

**Comment by alebyk113** [comment]
I am currently having the same issue with Uniform and DiscreteUniform 

    parameter1 = pm.Uniform('parameter1',0.01,1)
    parameter2 = pm.Uniform('parameter2',0,2)
    parameter3 = pm.DiscreteUniform('parameter3',1,10)
    parameter4 = pm.Uniform('parameter4',0,1.75)
    parameter5 = pm.Uniform('parameter5', 0.005, 0.25)
    parameter6 = pm.Uniform('parameter6', 0.005, 0.15)

    @pm.potential
    def log_l(experiment=experiment,parameter1=parameter1,parameter2=parameter2,parameter3=parameter3,parameter4=parameter4,parameter5=parameter5,parameter6=parameter6)    
    parameters=[parameter1, parameter2, parameter3]
        log_l=calculate_probability(parameters, t_m, tol, n_integration, parameter4, parameter5, parameter6, experiment.decon_all[freq,:,:])

        return log_l
    model = pm.MCMC([parameter1,parameter2,parameter3,parameter4,parameter5,parameter6,log_l])
    model.use_step_method(pm.Slicer, parameter1, w=0.05)
    model.use_step_method(pm.Slicer, parameter2, w=0.05)
    model.use_step_method(pm.Slicer, parameter3, w=1)
    model.use_step_method(pm.Slicer, parameter4, w=0.1)
    model.use_step_method(pm.Slicer, parameter5, w=0.025)
    model.use_step_method(pm.Slicer, parameter6, w=0.025)
    model.sample(100)

I was wondering if I am potentially doing something wrong or if that's a real issue?
