### ISSUE TITLE
Example implementation of LDA in PyMC

### ISSUE THREAD

**Issue by napsternxg** [pymc-devs/pymc2#44]
I have just started using PyMC for some of the NLP Topic Modelling work and wanted to implement Topic Models using LDA. However, there close to no documentation in PyMC and also on other websites about how to do it. There is one suggestion implementation posted at http://stats.stackexchange.com/questions/104771/latent-dirichlet-allocation-in-pymc which tries to build the LDA model. I have made a version of that and tested in on one of the standard corpuses but I am not sure how good the implementation is. 

Since Bayesian models are frequently used in NLP and topic models are one of the building blocks, I would suggest PyMC team to add an LDA or any NLP specific example in PyMC code so that individuals from NLP community can use it. 

My implementation and some analysis on Inaugural speech corpus can be seen at: https://github.com/napsternxg/ipython-notebooks/blob/master/PyMC_LDA.ipynb

**Comment by fonnesbeck** [comment]
There has been a recent burst of interest regarding LDA in PyMC. I have done a few small projects that include Dirichlet processes, but not LDA myself. As far as specific code for dealing with such applications, it would be more likely to happen under [PyMC 3](https://github.com/pymc-devs/pymc3) than under this version. PyMC 2 is essentially just being maintained in its current state, with new features and functionality developed in PyMC 3.

**Comment by napsternxg** [comment]
I am not saying specific code because I don't think that fits into the design feature of PyMC as a general purpose library. What I am suggesting is to add an example case either in the docs or the examples folder just like some of the other examples as that would give individuals in NLP field to try out PyMC for their models. Personally, I feel the framework of PyMC can encourage people to try out all the complex graphical models used in NLP and implement their python code instead of relying on rare and complex matlab examples.

**Comment by icoxfog417** [comment]
I agree with @napsternxg,  It's the issue of the variation of the examples, not the new feature.

But I worry about the practicability of using PyMC to implement LDA model.
Because I made LDA model by PyMC based on @napsternxg implementation and [this tutorial](http://alfan-farizki.blogspot.jp/2015/07/pymc-tutorial-3-latent-dirichlet.html).  Then it causes Memory Error (only hundreds of document).

I think this error relates to [Memory issue](https://github.com/pymc-devs/pymc/issues/5).  So we may have to overcome this problem to use PyMC to LDA.

**Comment by ghost** [comment]
@icoxfog417  Did you sample the model with Gibbs sampling or collapsed Gibbs sampling? Is it possible to implement LDA with collapsed Gibbs sampling with PyMC? Thanks in advance
