### ISSUE TITLE
Bernoulli variable does not follow requested probability in pymc model selection

### ISSUE THREAD

**Issue by jfmoulin** [pymc-devs/pymc2#48]
Below is a short pymc 2.3 script where I am trying to do model selection. My problem is the behaviour of the Bernoulli variable used as a model selector.

1) from the print statements I see that even with a high realization probability (promin >.9) the Bernoulli cast ber seems to be False most of the time (see below). This leads one of the two models never to be tried (here the parabola). I tried exchanging the order of return of the function (if ber: return linear model instead of parabolic) to rule out a very fast convergence. No effect. 
sampler.ber.trace[:] shows only False values. Only if pro is set to 1, the ber.trace[:] shows True values (all values True indeed, as expected)

2) incidently, my debug prints show that the fn is called much more often than the 100 times requested by the sampler. Why? I have no burn nor thin parameter...

3) the trace of ber and the content of ber_list are different (although the trace contains only Falses, the ber list shows some Trues.). This could be related to (2)...

I tried some simple models using Bernoulli distributions and they were fitted perfectly. But this switching model seems to be willing to drive me nuts. Hope I did not miss any critical stuff in the manual...

``` python

import pylab as p
import pymc
import pymc.Matplot

# example data. A very noisy parabola
x = p.arange(0,10,.1)
noise = p.randn(len(x)) * 16
err = p.ones(len(x)) * p.std(noise)
tau = 1 / err
y_real = .7 * x **2 - 5 * x + 42.69
y = y_real + noise

# priors for two models, a parabolic one and a linear one
a3 = pymc.Uniform('a3',0,4,2)
b3 = pymc.Uniform('b3',-20,20,-6)
c3 = pymc.Uniform('c3',-100,100,42)

a4 = pymc.Uniform('a4',0,1000.,35)
b4 = pymc.Uniform('b4',-100,100,1.8)

# a model switching variable, as Bernoulli cast (here very skewed)
# the posterior value of pro should give an indication of the best model
# among the two proposed.

promin= .99 ## edit : very high value only for demonstration purpose. Normally I would use 0.
promax = 1

pro = pymc.Uniform( "pro", promin , promax)
ber = pymc.Bernoulli( "ber", p = pro)

# the fitting function
verbose = True # try this only for small values of niter ;)
ber_list = []
@pymc.deterministic
def choose_model(a3=a3, b3=b3, c3=c3, a4=a4, b4=b4, ber=ber):
    ber_list.append(ber)
    if verbose:
        print ber
    # switching model as a fn of the Bernoulli cast
    if ber:
        return a3 * x**2 + b3 * x + c3
    else:
        return a4 * x + b4

# once fitted, the observation should be normally distributed around 
# the model fn
distry = pymc.Normal('distry', mu=choose_model, tau=tau, value=y, 
                     observed=True)

# packing everything into a Model
model = pymc.Model({'a3'     :    a3,
                    'b3'      :    b3,
                    'c3'      :    c3,
                    'a4'      :    a4,
                    'b4'      :    b4,
                    'ber'     :    ber,
                    'pro'     :    pro
                  })
# short sampling (better for diagnostics, should not have converged yet. And, yes I tried with much longer samplings)
sampler = pymc.MCMC(model)
sampler.sample(100)
```

**Comment by fonnesbeck** [comment]
Your uniform is constrained between 0.99 and 1? This seems odd, and will probably take a long time to converge. Why have it a random variable at all when you are so confident the value is almost 1?

Also, its not clear what `ber_list` is for, since the `ber` parameter will contain all these values.

**Comment by jfmoulin** [comment]
Well, the uniform is constrained to this meaningless value for demonstration purposes: as I wrote above, even with this very high probability I see that sampler.ber.trace[:].any() is False! Only way to get ber.trace[:].any() to be True is to set the probability to exactly 1. 
My initial plan was of course to fit between 0 and 1 and see if I can decide between the two models. Seing that my model _never_ tried the function which should have been sampled when ber==True, I biased the value to figure out was going on. 

The reason I used ber_list is along the same lines: activating my debug print statements I realized that I  actually had some ber==True popping out but not showing in ber.trace[:]! So I used this variable to count these events. They actually show up in a periodic pattern 1 True, 6 False. (whatever the value of pro in ]0,1[. If pro == 0, I get only Falses if pro == 1 only Trues.)

Returning to the old school print debugging I also realized that my print was executed more often than the value of niter, even though I tried without burning nor thinning.

I hope this clarifies the problem, thanks for having a look at it!

**Comment by fonnesbeck** [comment]
Looking at this a little more closely, it looks like your smaller model returns values that are a couple of orders of magnitude larger than the values for the larger model. So, that may be explaining to some extent why one model is never being chosen. I've reformulated things a little:

``` python
import pylab as p
import pymc
import pymc.Matplot

# example data. A very noisy parabola
x = p.arange(0,10,.1)
noise = p.randn(len(x)) * 16
err = p.ones(len(x)) * p.std(noise)
tau = 1 / err**2
y_real = .7 * x **2 - 5 * x + 42.69
y = y_real + noise

# priors for two models, a parabolic one and a linear one
a3 = pymc.Uniform('a3',0,4, value=2)
b3 = pymc.Uniform('b3',-20,20, value=-6)
c3 = pymc.Uniform('c3',-100,100, value=42)

a4 = pymc.Uniform('a4',0,1000., value=35)
b4 = pymc.Uniform('b4',-100,100, value=1.8)

# a model switching variable, as Bernoulli cast (here very skewed)
# the posterior value of pro should give an indication of the best model
# among the two proposed.

promin= 0 ## edit : very high value only for demonstration purpose. Normally I would use 0.
promax = 1

pro = pymc.Uniform( "pro", promin , promax)
ber = pymc.Bernoulli( "ber", p = pro, value=True)

m1 = pymc.Lambda('m1', lambda a3=a3, b3=b3, c3=c3: a3 * x**2 + b3 * x + c3, trace=False)
m2 = pymc.Lambda('m1', lambda a4=a4, b4=b4: a4 * x + b4, trace=False)

mu_chosen = pymc.Lambda('mu_chosen', lambda m1=m1, m2=m2, ber=ber: [m1, m2][int(ber)])

# once fitted, the observation should be normally distributed around 
# the model fn
distry = pymc.Normal('distry', mu=mu_chosen, tau=tau, value=y, 
                     observed=True)

# packing everything into a Model
sampler = pymc.MCMC(locals())
# short sampling (better for diagnostics, should not have converged yet. And, yes I tried with much longer samplings)
sampler.sample(10000, burn=5000)
```

**Comment by fonnesbeck** [comment]
You have to be very careful about setting this model up, because if the current estimates of the parameters are not competitive for any given model, it may never get a chance to be selected again because its parameters are never being improved by the likelihood function, since only one model is connected to the likelihood at any given iteration. I would use DIC to do model selection for a scenario like this.

**Comment by jfmoulin** [comment]
1) I tried the method with with "experimental data" being a noisy straight line and the above two models (so that the parabola is overfiting) and for some chains it seemed to work. But for some chains I saw that, even though the probability of the Bernoulli realization is described by a uniform prior (0 to 1), a model is chosen 100% of the time. I understand the argument of competitivity, but I would expect each model to get its chance at the very least once... (you will probably agree since you mention "... to be selected again..")

2) Regarding the use of DIC, I read that It is only valid when the posterior distribution is approximately multivariate normal. I am not quite sure this will be the case for my actual problem (the example above was a toy system for me to learn. What I am trying to fit is a problem where the chi2 landscape as very many local minima and most probably not a single global minimum (I am looking at crystallography data for which there maybe sets of parameters which due to symmetry effects produce the _exact_ same simulation). This has to be reflected in the posteriors.
A trivial question to end with: where do I find the DIC? I found AIC and BIC as properties of a MAP but cannot find DIC or dic... I looked at sampler.trace[:].deviance, is this what I am looking for?

**Comment by fonnesbeck** [comment]
The `MCMC` class has a `DIC` attribute (unless you turn off `calc_deviance`).

Each model gets a chance when the value for `ber` is proposed, but all it has to go on is the log probability under each model, conditional on the current values of its parameters, so you want to make sure its values are competitive from the start. What `MCMC` needs here, perhaps, is some tempering that will (temporarily) make poor models competitive. In the meantime, you could find reasonable model parameters for each model, perhaps, using MAP and initialize the model that way.

One other alternative is to fit both models, and compare them using Bayes factors.
