### ISSUE TITLE
pymc imput passing back 1e20

### ISSUE THREAD

**Issue by jjkernst** [pymc-devs/pymc2#49]
In the masked method of impute the object passes 1e20 for nan/None elements rather than samples from the specified distribution. I have compared the same matrix with the Impute function and it seems to have correct samples from the distribution. Below is a small sample code to illustrate the issue. 

I am pretty new to pymc so maybe this is a limitation to the masked approach that is not present with the Impute method? 

```
import numpy as np
import pymc as py

disasters_array = np.random.random((3,3))
disasters_array[1,1]=None

D = py.Impute('D', py.Normal, disasters_array, mu=.5, tau=1E5)

print disasters_array
masked_values = np.ma.masked_invalid(disasters_array)

disasters = py.Normal('disasters', mu=.5, tau=1E5, value=masked_values, observed=True)
@py.deterministic
def test(disasters=disasters, D=D):
    print D
    print disasters

mcmc = py.MCMC(py.Model(set([test,disasters])))
```

Output:

Original Matrix:

```
[[ 0.23507836  0.2024624   0.90518228]
 [ 0.95816            **nan**  0.43145808]
 [ 0.99566308  0.25431568  0.25464137]]
```

D with imputations:

```
[[array(0.23507836309832741) array(0.20246240248367342)
  array(0.9051822818081371)]
 [array(0.9581599997650212) **array(0.5005324083232756)**
  array(0.43145807852698237)]
 [array(0.9956630757864052) array(0.2543156788973996)
  array(0.25464136701826867)]]
```

Masked Array approach:

```
[[  2.35078363e-01   2.02462402e-01   9.05182282e-01]
 [  9.58160000e-01   **1.00000000e+20**   4.31458079e-01]
 [  9.95663076e-01   2.54315679e-01   2.54641367e-01]]
```

Post from stackoverflow: http://stackoverflow.com/questions/31934287/pymc-imput-passing-back-1e20

**Comment by fonnesbeck** [comment]
You don't need to use `Impute` directly. Just pass a masked array to an observed stochastic, and it will impute. So, get rid of `D` in the above.

Which version of PyMC are you using?

**Comment by jjkernst** [comment]
Thanks Chris, Should have mentioned the version: 2.3.4. 

Above impute is used only to illustrate the masked functionality doesn't seem to be working properly. The Impute function not using the mask works as it should, while the masked approach sends erroneous values (1e20). Below is another example where I attempt to use masked and receive an error where the same array replaced with a None instead of a nan, will work.  

I have a dataset that is being read in from a file with missing numbers, and when I attempt to use the masked impute it either throws the below error, or passes 1e20. 

disasters_array = array([4.4, np.NAN, 4.4, 0, 1, 4, 3, 4, 0, 6, 3, 3, 4, 0, 2])
masked_values = np.ma.masked_invalid(disasters_array)
disasters = Poisson('disasters', mu=.5, value=masked_values, observed=True)
mcmc=MCMC(Model({'disasters':disasters}))
mcmc.sample(iter=50)

Error: "pymc.Node.ZeroProbability: Stochastic disasters's value is outside its support, or it forbids its parents' current values."

But this work:
disasters_array = array([4.4, None, 4.4, 0, 1, 4, 3, 4, 0, 6, 3, 3, 4, 0, 2])
masked_values = np.ma.masked_equal(disasters_array,value=None,copy=False)
disasters = Poisson('disasters', mu=.5, value=masked_values, observed=True)
mcmc=MCMC(Model({'disasters':disasters}))
mcmc.sample(iter=50)

**Comment by jjkernst** [comment]
It seems for the masked impute to work, the masked array must be dtype =object and missing values must be marked by None, only. 

Changed disasters_array to object type and replacing all nan's with None and it seems to work. (Below is code) 

disasters_array = np.array([4.4, np.NAN, 4.4, 0, 1, 4, 3, 4, 0, 6, 3, 3, 4, 0, 2])
disasters_array=disasters_array.astype(object)
disasters_array[np.isnan(disasters_array)]=None
masked = np.ma.masked_equal(disasters_array, value=None)
disasters = Poisson('disasters', mu=.5, value=masked_values, observed=True)
mcmc=MCMC(Model({'disasters':disasters}))
mcmc.sample(iter=50)
