### ISSUE TITLE
Restore Sample Method State from hdf5 database

### ISSUE THREAD

**Issue by Leguark** [pymc-devs/pymc2#58]
I am trying to restore the Sample Method State of a chain, specially the adaptive scale factors of Metropolis.

Loading the data base and getting the state, all information is perfectly stored in a dictionary. However, the `function restore_sampler_state()` does not restore the "step methods" and the function `restore_sm_state()` does not seem to do anything. I am wondering if I am doing something wrong or is a bug.

If the problem is that is not implemented, I guess that the fastest way to do so, is to use the `use_step_method` function and read the info from the database dictionary?

Thanks for the help!

**Comment by fonnesbeck** [comment]
The sampler state restoration really only works well with the HDF5 backend. Which are you using?
