### ISSUE TITLE
Trouble installing 2.3.6 on Mac OS X 10.10.4

### ISSUE THREAD

**Issue by dean-shaff** [pymc-devs/pymc2#65]
Hey there,

I'm having trouble installing pymc for python 2.7. My gfortran version is 5.2.0, and my gcc version is "Apple LLVM version 6.1.0". I get the following error when I try to install with pip: 

error: Command "/usr/local/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -arch x86_64 -fPIC -O3 -funroll-loops -DNO_ATLAS_INFO=3 -Ibuild/src.macosx-10.10-intel-2.7 -I/Library/Python/2.7/site-packages/numpy-1.9.0-py2.7-macosx-10.9-intel.egg/numpy/core/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c -c pymc/flib.f -o build/temp.macosx-10.10-intel-2.7/pymc/flib.o" failed with exit status 1

**Comment by fonnesbeck** [comment]
Your fortran compiler is not compatible with your c compiler. You need to pick your fortran accordingly. The way I do it is to use the gcc from Homebrew, which includes fortran.
