### ISSUE TITLE
Documentation on Creating Models gives examples on how to instantiate `Model` objects directly

### ISSUE THREAD

**Issue by fbnrst** [pymc-devs/pymc2#74]
According to #68 one should not gives examples on how to instantiate `Model` objects. However, the section [5.1 Creating models](http://pymcmc.readthedocs.org/en/latest/modelfitting.html#creating-models) explicitly gives examples on how to instantiate `Model` objects. 
Should the examples be rewritten such that they use a `Model` subclass like `MCMC`. The docs could mention that other subclasses like `MAP` could also be used.

**Comment by fonnesbeck** [comment]
The documentation in section 5.1 says "once you have defined the nodes that make up your model, you shouldn’t even have to think about how to wrap them in a Model instance". However, I agree that the examples should probably use a`Model` subclass. I will change this.

**Comment by fonnesbeck** [comment]
Let me know if these changes are not a sufficient clarification.

**Comment by fbnrst** [comment]
Looks very good! Maybe one more thing concerning the docs: They say that you could use the `fit` function of a `MAP` object to `finding reasonable initial states for MCMC chains.` 
Now, I saw several examples on stackexchange.com where people would first instantiate a `Model` and from this `Model` they instantiate a `MAP` and a `MCMC`. The you first fit and then run MCMC.
Now the docs suggest you should directly instantiate the `MAP` and the `MCMC`. However, if you do your instantiation with a model factory function:

``` python
map_ = pymc.MAP(make_model())
mcmc = pymc.MCMC(make_model())
```

 `MAP` and `MCMC` do not handle "the same collection of nodes." Or do they?
Maybe the docs should have an example how to do the first fit then mcmc thing. Because I currently do not know what the best option is to avoid the issue that people instantiate `Model` because of this.

**Comment by fonnesbeck** [comment]
Sorry for the late reply. One way to use the model fit by MAP in a MCMC simulation is to do something like the following:

```
map_ = pymc.MAP(make_model())
map_.fit()
mcmc = pymc.MCMC(map_.variables)
```
