### ISSUE TITLE
Test failures on Python 3.5 on MacPorts 2.3.4/OS X 10.10

### ISSUE THREAD

**Issue by Russell-Jones-OxPhys** [pymc-devs/pymc2#75]
Hi, I'm updating the py-pymc MacPort, and running pymc.tests.test() in Python 3.5 gives a lot of instances of

```
DeprecationWarning (inspect.getargspec() is deprecated, use inspect.signature() instead)
```

Let me know if I should cut and paste, but I'd think a simple [search of the repository](https://github.com/pymc-devs/pymc/search?utf8=%E2%9C%93&q=getargspec) would be more useful. getargspec() will be [removed in 3.6](https://docs.python.org/3/library/inspect.html#classes-and-functions) and signature() isn't in 2.7 so I guess the code will need to check for 2 or 3.

**Comment by fonnesbeck** [comment]
Please test PR

**Comment by fonnesbeck** [comment]
Never mind. This won't work. Stay tuned.

**Comment by fonnesbeck** [comment]
Should be fixed now. Please test master.

**Comment by Russell-Jones-OxPhys** [comment]
Thanks, I couldn't get it to link correctly in a VE, so I'll need to rejig the Portfile to use a checkout rather than a release tag. I will get back to you when I've done that.

**Comment by Russell-Jones-OxPhys** [comment]
Well, that was easier than I thought it might be :) Yes, all tests pass (8 skipped) for 5759218

**Comment by fonnesbeck** [comment]
Excellent, thanks.
