### ISSUE TITLE
Multi-panel forrest plot

### ISSUE THREAD

**Issue by mamacneil** [pymc-devs/pymc2#77]
I am struggling to pass PyMC's summary_plot argument through to create two panels of parameter estimates - I feel like I should be able to pass recursive ax arguments along the lines of what I have below but I'm fumbling. I'd like to display these side by side for a ZI model. Any help would be much appreciated!

```
npan = 2
fig, axes = plt.subplots(nrows=1, ncols=npan, figsize=(7,10))

# Zero Component
ax = axes.flat[0]
pm.Matplot.summary_plot([M.kappa_0]+[x for x in M.Kappa1],axis=ax)

# Count Component
ax = axes.flat[1]
pm.Matplot.summary_plot([M.gamma_0]+[x for x in M.Gamma1],axis=ax)
```

**Comment by fonnesbeck** [comment]
That's because `summary_plot` is already a multi-axis plot that uses `GridSpec`, so it does not take an `axis` argument. Would have to think about how to do this.

**Comment by mamacneil** [comment]
Ah so - I'll just pull the traces in the meantime; thanks much
