### ISSUE TITLE
missing gfortran in osx10.11

### ISSUE THREAD

**Issue by chenminhua** [pymc-devs/pymc2#79]
I try to install pymc, but I got an error which told me that I don't have fortran compiler
so I try to _brew install gfortran_
it told me I should _brew install gcc_ (but I already have gcc)
so I do _brew install gcc_
but I got another error **Error: Failed to download resource "mpfr--patch"** 
And I can't figure out that. Please help me

**Comment by fonnesbeck** [comment]
You need to ensure that your Fortran compiler is compatible with your gcc. If your gcc came from someplace other than home brew then you need to find a Fortran compiler that works with it. If you are having homebrew issues, you should open an issue with that project.
