### ISSUE TITLE
Different results with PyMC versions 2.3.2 and 2.3.6

### ISSUE THREAD

**Issue by rcrehuet** [pymc-devs/pymc2#82]
If I execute the following code in Python 2.7 and PyMC 2.3.2 I get a different result than when I use Python 3.4 and PyMC 2.3.4.
In the first case, I get two distributions that are equal, as I would expect. With Python 3 and PyMc 2.3.4 the results depend on the `shift`.

```
import pymc as pm
import matplotlib.pyplot as plt

N = 100
shifts = (0, -1)
for shift in shifts:
    obs_mean = 3.5
    obs_total = int(N*obs_mean)
    sigma = 0.01*N
    dice = pm.DiscreteUniform('dice', 1+shift, 6+shift, size=N)

    @pm.deterministic
    def dice2(d=dice):
        return d-shift

    @pm.deterministic
    def calc_total(d=dice2):
        return np.sum(d)

    total = pm.Normal('total', mu=calc_total, tau=1./sigma, observed=True, value=obs_total)

    # package the full model in a dictionary
    model1 = dict(dice=dice, dice2=dice2, calc_total=calc_total, total=total)

    # run the basic MCMC:
    S = pm.MCMC(model1)
    S.sample(iter=100000, burn=10000)

    dice_trace = S.trace('dice2')[:]
    plt.hist(dice_trace.flat, bins=(0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5), normed=True, alpha=0.5)

plt.show()
```

My understanding is that `shift` should not affect the result, as `dice2` is always a uniform distribution from 1 to 6, and that is what determines the likelihood. Printing the histogram output gives the following.
Python 2.7 results:

```
array([ 0.165365  ,  0.16800544,  0.16617056,  0.16799411,  0.16658656, 0.16587833]
array([ 0.16591211,  0.16620856,  0.16819433,  0.16682722,  0.16761944, 0.16523833]
```

Python 3.4 results:

```
array([ 0.165365  ,  0.16800544,  0.16617056,  0.16799411,  0.16658656, 0.16587833]
array([ 0.11427189,  0.210576  ,  0.19239633,  0.17393467,  0.16024644, 0.14857467]
```

**Comment by fonnesbeck** [comment]
Actually, I get the your Python 2.7 behavior under both versions of Python on my machine. 

BTW, do you have a reference (paper, book chapter) for this problem?

**Comment by fonnesbeck** [comment]
You forgot to shift `obs_total`. They will be different when you shift the values of the die faces. My version of the code below includes simulation of data:

```python
import pymc as pm
import matplotlib.pyplot as plt
import numpy as np

N = 100
shifts = (0, -1)

np.random.seed(42)

for shift in shifts:

    data = pm.rdiscrete_uniform(1+shift, 6+shift, size=N)
    print('Observed mean is', data.mean())
    obs_total = sum(data)
    print('Observed total is', obs_total)
    sigma = pm.Uniform('sigma', 0, 1000, value=1)
    dice = pm.DiscreteUniform('dice', 1+shift, 6+shift, size=N)

    @pm.deterministic
    def dice2(d=dice):
        return d-shift

    @pm.deterministic
    def calc_total(d=dice2):
        return np.sum(d)

    total = pm.Normal('total', mu=calc_total, tau=1./sigma, observed=True, value=obs_total)

    # package the full model in a dictionary
    model1 = dict(dice=dice, dice2=dice2, calc_total=calc_total, total=total)

    # run the basic MCMC:
    S = pm.MCMC(model1)
    S.sample(iter=100000, burn=10000)

    dice_trace = S.trace('dice2')[:]
    h = plt.hist(dice_trace.flat, bins=(0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5), normed=True, alpha=0.5)
    print(h)
```

**Comment by rcrehuet** [comment]
No, I didn't forget to update `obs_total`. It's a contrived example because I wanted to see if I could generate a uniform distribution from 1 to 6 from a uniform distribution in a different range (the reason being that I wanted to use Categorical in a following step, and Categorical samples from 0 to 5).

Having said that, I still get different results running your code. Probably the reason stem from the pyMC version or one of its dependencies. Here are my results for your code (and your seed):

Python 2.7, pyMC 2.3.2, Numpy 1.8.2

```
array([ 0.14029167,  0.14788244,  0.16302   ,  0.172375  ,  0.18395778, 0.19247311]
array([ 0.39038878,  0.24716156,  0.15651967,  0.10136933,  0.06269989, 0.04186078]
```

Python 3.4, PyMC 2.3.4, Numpy 1.10.1

```
array([ 0.14134589,  0.14888633,  0.16132122,  0.17030867,  0.18369367, 0.19444422]
array([ 0.270009  ,  0.32260911,  0.190304  ,  0.11364011,  0.06622589, 0.03721189]
```

Is there anything I can do to trace the source of the problem? Or some test cases I could pass to see what it affects?

As for the dice, several works have addressed the different outcomes when using the Maximum Entropy principle or a Bayesian approach. I was using an fair dice, but loading the dice is trivial, of course. Some of the references also discuss the fair dice.
Uffink wrote one of the [early papers](http://www.sciencedirect.com/science/article/pii/1355219895000224). Two recent papers are the ones by [van Enk](http://arxiv.org/abs/1408.6803) and   by [Neapolitan](http://www.mdpi.com/1099-4300/16/7/4004).

**Comment by rcrehuet** [comment]
Indeed, the question doesn't seem to come from the Python version, but from the PyMC version. On a different machine I get in both cases the _suspicious_ results.
- Python 2.7, **PyMC 2.3.6**, Numpy 1.8.2 

``` python
array([ 0.16301511,  0.16851878,  0.16897833,  0.167536  ,  0.16907367, 0.16287811])
array([ 0.11373644,  0.20983978,  0.19086644,  0.17790478,  0.16271556, 0.144937  ])
```
- Python 3.4, **PyMC 2.3.6**, Numpy 1.10.1

``` python
array([ 0.16388167,  0.16813344,  0.16816811,  0.16834333,  0.16687344, 0.1646    ])
array([ 0.11253578,  0.20900689,  0.19531956,  0.17652178,  0.16141822, 0.14519778])
```

whereas going back to version 2.3.2 I get the _expected_ results (equal distributions for both shifts):
- Python 2.7, **PyMC 2.3.2**, Numpy 1.8.2

``` python
array([ 0.16578222,  0.16674911,  0.16654344,  0.16846711,  0.16742956, 0.16502856])
array([ 0.16793333,  0.16488189,  0.16771922,  0.16506778,  0.16738367, 0.16701411])
```

So I guess the problem is in PyMC version 2.3.6. Therefore I edited to subject.

**Comment by fonnesbeck** [comment]
Very odd. Thanks for digging into it. I will see if I can track down the problem.

**Comment by fonnesbeck** [comment]
I notice that it appears to be fine when using a positive shift (say, +1, +2). Negative shifts are what appear to cause the problems.

**Comment by fonnesbeck** [comment]
The issue appears not to be with the normal likelihood, as substituting a student-T likelihood also returns a spurious result.

**Comment by fonnesbeck** [comment]
However, it also appears that the `DiscreteUniform` samples correctly, based on the following simple test case:

``` python
import pymc as pm
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

shift = -2
d = pm.DiscreteUniform('d', 1+shift, 6+shift)

M = pm.MCMC(locals())
M.sample(10000)
print(pd.Series(d.trace()[:].flat).value_counts())
```

which results in:

```
 1    1698
 4    1683
 3    1678
 0    1666
 2    1638
-1    1637
```

I'm stumped on this one.

**Comment by rcrehuet** [comment]
Indeed, it's really strange. As you say, the issue is with negative shifts. But it's not an issue with `DiscreteUniform` because the disagreeing results are obtained also with `Categorical`. For Example:

``` python
import numpy as np
import pymc as pm
import matplotlib.pyplot as plt

N = 100
obs_mean = 3.5
obs_total = int(N*obs_mean)
sigma = 0.01*N
shift = -1
dice = pm.Categorical('dice',np.ones(6)/6., size=N)

@pm.deterministic
def dice2(d=dice):
    return d-shift

@pm.deterministic
def calc_total(d=dice2):
    return np.sum(d)

total = pm.Normal('total', mu=calc_total, tau=1./sigma, observed=True, value=obs_total)

# package the full model in a dictionary
model1 = dict(dice=dice, dice2=dice2, calc_total=calc_total, total=total)

# run the basic MCMC:
S = pm.MCMC(model1)
S.sample(iter=100000, burn=10000)

dice_trace = S.trace('dice2')[:]
print(plt.hist(dice_trace.flat, bins=(0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5), normed=True, alpha=0.5))

plt.show()
```

**Comment by rcrehuet** [comment]
On the other hand, even a uniform likelihood gives unexpected results, as in the example below. So it must be somewhere in the acceptance rule of MC...

``` python
import numpy as np
import pymc as pm
import matplotlib.pyplot as plt

N = 100
obs_mean = 3.5
obs_total = int(N*obs_mean)
sigma = 0.01*N
shift = -1
#Make sure initial value is valid for the likelihood
dice_val = np.ones(100, dtype=np.int)*3
dice_val[:50] = 2
dice = pm.DiscreteUniform('dice',0, 5, size=N)
dice.set_value(dice_val)

@pm.deterministic
def dice2(d=dice):
    return d-shift

@pm.deterministic
def calc_total(d=dice2):
    return np.sum(d)

total = pm.Uniform('total', calc_total-2, calc_total+2, observed=True, value=obs_total)

# package the full model in a dictionary
model1 = dict(dice=dice, dice2=dice2, calc_total=calc_total, total=total)

# run the basic MCMC:
S = pm.MCMC(model1)
S.sample(iter=100000, burn=10000)

dice_trace = S.trace('dice2')[:]
print(plt.hist(dice_trace.flat, bins=(0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5), normed=True, alpha=0.5))

plt.show()
```

Please tell me if I can help any further. I'm glad to collaborate, but I don't know what could be the next step.

**Comment by fonnesbeck** [comment]
OK, I think I figured it out. Its the proposals for the `DiscreteUniform`. Try adding the following line just prior to calling `sample`:

```
S.use_step_method(pm.DiscreteMetropolis, dice, proposal_distribution='Prior')
```

**Comment by fonnesbeck** [comment]
And, it looks like this tweak works too:

```
S.use_step_method(pm.DiscreteMetropolis, dice, positive=False)
```

**Comment by rcrehuet** [comment]
Great! Both work. And it also works with `Categorical`.
Could you give some explanation of when could this be an issue?

**Comment by fonnesbeck** [comment]
By default, the `DiscreteMetropolis` step methods proposes positive-only values, since discrete variables are almost always positive in practice. Hence, negative values are never being proposed.

**Comment by rcrehuet** [comment]
Thanks! I think 0 (zero) should be part of the default, as `Categorical` includes this value by default.

So as far as I understand, `positive=False` is the argument that should give equivalent results for both positive and negative priors, whereas `proposal_distribution='Prior'` implies sampling from a different distribution from the default one, which could potentially affect the rate of convergence (but not the converged results).

**Comment by fonnesbeck** [comment]
OK, I have pushed a fix to the `discrete_fix` branch that should deal with things automatically in a more sensible way. If you can, please test.

```
pip install -U git+git://github.com/pymc-devs/pymc.git@discrete_fix
```

**Comment by rcrehuet** [comment]
Seems to be working fine with my previous examples. I see you have removed the `positive` arguement to `use_step_method`.
Thanks for your time!

**Comment by fonnesbeck** [comment]
Actually, I changed the argument to `non_negative`, since it does allow zeros.

Happy that it works. I will merge it.
