### ISSUE TITLE
Segmentation fault on OSX

### ISSUE THREAD

**Issue by kyleabeauchamp** [pymc-devs/pymc2#83]
Has anyone noticed a lot of segmentation faults on OSX?  I imagine it's a memory leak in the fortran code under the hood.  It generally tends to happen right after I finish sampling a model.  The same piece of code only crashes say ~20% of the time.  

```
~/anaconda2/bin/python.app: line 3: 39452 Segmentation fault: 11  ~/anaconda2/python.app/Contents/MacOS/python "$@"
```

**Comment by kyleabeauchamp** [comment]
I think I've seen it for the last 1-2 pymc releases, FWIW.  And with multiple numpy versions and anaconda versions.

**Comment by fonnesbeck** [comment]
I can't remember my last Python segfault. Are you using Conda builds, or your own pip?

**Comment by kyleabeauchamp** [comment]
Conda builds.

**Comment by fonnesbeck** [comment]
I am always running PyMC in develop mode from pip, so that may explain my lack of issues. Hopefully folks will chime in here if they are having conda build issues. Are you on PyMC 2.3.6?

**Comment by kyleabeauchamp** [comment]
Yep.  2.3.6 and numpy 1.10.1

This one isn't super urgent, I just thought I'd open it so we can collect data from other users to see if it's common.

**Comment by kyleabeauchamp** [comment]
So I found a workaround: use `python` rather than `ipython`.  For some reason, I can only reproduce the bug in an interactive session.  I'll close this for now unless someone else re-discovers it.

**Comment by Russell-Jones-OxPhys** [comment]
@kyleabeauchamp Which version of ipython, JOOI?

**Comment by kyleabeauchamp** [comment]
Python 2.7.11 |Anaconda 2.4.1 (x86_64)| (default, Dec  6 2015, 18:57:58)
IPython 4.0.1 -- An enhanced Interactive Python.
