### ISSUE TITLE
ZeroDivisionError: float division by zero in NormalApproximation.py

### ISSUE THREAD

**Issue by bjlkeng** [pymc-devs/pymc2#86]
Hi, I was fitting a `Lognormal()` model using `pymc.MAP()` and got this error:

```
File ".../local/lib/python2.7/site-packages/pymc/NormalApproximation.py", line 371, in fit
self.AICc = self.AIC + ((2 * self.len * (self.len + 1)) / float(self.data_len - self.len - 1))
ZeroDivisionError: float division by zero
```

Somehow it got a divide by zero but if I comment out the line, my the MAP estimates seem fine.  Should the `AICc` calculation be wrapped in a `try/except` block like the `BIC` calculation?

I'm using `pymc==2.3.6` and Python 2.7.6 on Ubuntu.

**Comment by fonnesbeck** [comment]
Can you post a minimal example that shows the behavior? Is it _any_ Lognormal model?

**Comment by bjlkeng** [comment]
Sure, let me spend some time trying to extract one.  I was actually fitting many small models in parallel using PySpark so it's not obvious which one failed but I'll try to figure it out and post it.

**Comment by bjlkeng** [comment]
Hi, here's a minimal test case: https://gist.github.com/bjlkeng/2601483c39b1b8ec63db
I discovered that the code only triggers the bug if I include a subset of the model variables when I pass it into `MAP()`.

**Comment by fonnesbeck** [comment]
I'm confused as to why all the variable aren't being passed to `MCMC`. If they aren't passed, then you don't have a complete DAG.

**Comment by fonnesbeck** [comment]
I did go ahead and improve exception handling for AIC/BIC in #89, so give that a try, but you should be passing all of the PyMC variables to the model. I recommend either passing `locals()` to `MCMC`, or wrapping your model definition in a function that returns `locals()`.

**Comment by bjlkeng** [comment]
Ahh... okay, good to know.  I thought it would still figure out the parents nodes without it.  Thanks for the tip, I'll make sure to do that in my code.

**Comment by aflaxman** [comment]
I'm running into this error as well. I can try to extract a minimal example if you demand it, but I'm going to fix it by wrapping the computation in a try/except block:
```
        try:
            self.AICc = self.AIC + ((2 * self.len * (self.len + 1)) / float(self.data_len - se\
lf.len - 1))
        except ZeroDivisionError:
            self.AICc = -Inf
```

**Comment by fonnesbeck** [comment]
@aflaxman are you using the current master? This exception (and all others) is caught [here](https://github.com/pymc-devs/pymc/blob/master/pymc/NormalApproximation.py#L375).
