### ISSUE TITLE
Binomial rv causes core dump with minimal example

### ISSUE THREAD

**Issue by vumaasha** [pymc-devs/pymc2#9]
``` python
import pymc as pm
from pymc import Beta,Binomial,Exponential
import numpy as np
from pymc.Matplot import plot as mcplot

data = pm.rbinomial(5,0.01,size=100)
p = Beta("p",1,1)
observations = Binomial("obs",5,p,value=data,observed=True)
model = pm.Model([p,observations])
mcmc = pm.MCMC(model)
mcmc.sample(400,100,2)
mcplot(mcmc)
```

```
venki@venki-HP-248-G1-Notebook-PC:~/Desktop$ python perf_testing.py 
*** glibc detected *** python: free(): corrupted unsorted chunks: 0x0000000003cb0d40 ***
*** glibc detected *** python: malloc(): memory corruption: 0x00000000038bf2e0 ***
```
## OS

Python 2.7.3
pymc 2.3.4
Ubuntu 12.04.5 LTS

**Comment by fonnesbeck** [comment]
I can't replicate this behavior here, but my system does not match yours. If possible, can you build from the current master and see if the behavior can be replicated? There have been some memory-related fixes since 2.3.4.

**Comment by vumaasha** [comment]
Sure. I will give it a try and update

**Comment by marcus-r-kelly** [comment]
I have also encountered this bug using Python 2.7.5 ; 
Linux 3.18.9-100.fc20.x86_64, Fedora 20
Also PyMC 2.3.4

**Comment by marcus-r-kelly** [comment]
The problematic code executes with no errors after upgrade to 2.3.5
