### ISSUE TITLE
setup.py doesn't automatically install numpy dependency

### ISSUE THREAD

**Issue by bjlkeng** [pymc-devs/pymc2#93]
Putting `pymc` in my `requirements.txt` and then running `pip install requirements.txt` on a fresh virtual environment errors out because `numpy` is not installed first.

This was a similar issue in `scikit-learn`: https://github.com/scikit-learn/scikit-learn/issues/4164
They're `setup.py` has a work around that only uses `numpy` during the actual install and for other `pip` commands, doesn't explicitly import it.  Is it possible to do the same thing with `pymc`?

**Comment by fonnesbeck** [comment]
But scikit-learn will still raise an error if NumPy is not there:

``` python
if numpy_status['up_to_date'] is False:
    if numpy_status['version']:
        raise ImportError("Your installation of Numerical Python "
                          "(NumPy) {0} is out-of-date.\n{1}{2}"
                          .format(numpy_status['version'],
                                  numpy_req_str, instructions))
    else:
        raise ImportError("Numerical Python (NumPy) is not "
                          "installed.\n{0}{1}"
                          .format(numpy_req_str, instructions))
```

so if `requirement.txt` does not have NumPy installed first, it would still fail.

**Comment by fonnesbeck** [comment]
The `numpy_setup` branch referenced above addresses this, but I'm not sure if its exactly what you are looking for.

**Comment by bjlkeng** [comment]
Yep, this is what I was expecting, thanks!  

My main concern was installing numpy + pymc in one call to pip instead two.  My use case was similar to scikit issue where I wanted to run some continuous integration tests running by creating a virtualenv.  Without a one step pip install, the virtualenv setup was quite a hassle.
